spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 8080

management:
  server:
    port: 8082
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

logging:
  level:
    root: INFO
    org:
      apache:
        activemq:
          artemis: DEBUG
