version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka0:
    build: .
    ports:
      - "9092"
    expose:
      - "9092"
    environment:
      KAFKA_LISTENERS: 0.0.0.0:9092,kafka-docker_kafka0_1:9092
      KAFKA_ADVERTISED_LISTENERS: 127.0.0.1:9092,kafka-docker_kafka0_1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "testTopic:1:3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka1:
    build: .
    ports:
      - "9093:9092"
    expose:
      - "9092"
    environment:
      KAFKA_LISTENERS: 0.0.0.0:9092,kafka-docker_kafka0_1:9093
      # KAFKA_ADVERTISED_LISTENERS: kafka-docker_kafka0_1:9092,kafka-docker_kafka1_1:9092,kafka-docker_kafka2_1:9092
      KAFKA_ADVERTISED_LISTENERS: 127.0.0.1:9092,kafka-docker_kafka0_1:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
      - "kafka0"
  kafka2:
    build: .
    ports:
      - "9094:9092"
    expose:
      - "9092"
    environment:
      KAFKA_LISTENERS: 0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: 127.0.0.1:9092,kafka-docker_kafka2_1:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
      - "kafka0"
      - "kafka1"
  producer_app:
   build: ./producerApp
   ports:
     - 8081:8080
   privileged: true
   depends_on:
     - "kafka0"
     - "kafka1"
     - "kafka2"
  consumer_app:
    build: ./consumerApp
    privileged: true
    depends_on:
      - "kafka0"
      - "kafka1"
      - "kafka2"
