scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets: ['cadvisor:8080']
- job_name: spring
  metrics_path: '/actuator/prometheus'
  scrape_interval: 3s
  static_configs:
  - targets: ['producerapp:8082','consumerapp:8082']
