spring:
  application:
    name: producer-service
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8080
logging:
  level:
    root:
    org:
      apache:
        activemq:
          artemis: DEBUG
