spring:
  application:
    name: producer-service
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8080
management:
  server:
    port: 8082
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
logging:
  level:
    root:
    org:
      apache:
        activemq:
          artemis: DEBUG
